name: Test
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST MULTIPLE JS VERSIONS
          - js_version: 10
          - js_version: 12
          - js_version: 14
          - js_version: 16

    steps:
      - uses: actions/checkout@v2

      - name: Install Javascript
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.js_version }}"

      - run: npm install

      - run: npm test
